import { bodyFont } from "@/utils/fonts";
import type { Metadata } from "next";
import "../styles/style.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
